// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANiUGxyO75D9WAM-mkOHx-e5L9cXTgFro',
    appId: '1:297570478095:web:a6f3a23f70842373645b7a',
    messagingSenderId: '297570478095',
    projectId: 'my-diplom-firebase',
    authDomain: 'my-diplom-firebase.firebaseapp.com',
    storageBucket: 'my-diplom-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfiIN7kyWNwKBM6mMn8fGddwMCzxLs6oA',
    appId: '1:297570478095:android:d8035d898993969f645b7a',
    messagingSenderId: '297570478095',
    projectId: 'my-diplom-firebase',
    storageBucket: 'my-diplom-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBs1VJljHj3ygqhZLQFiNjGjPKRYq2LQI',
    appId: '1:297570478095:ios:df06af22987fea31645b7a',
    messagingSenderId: '297570478095',
    projectId: 'my-diplom-firebase',
    storageBucket: 'my-diplom-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseDiplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBs1VJljHj3ygqhZLQFiNjGjPKRYq2LQI',
    appId: '1:297570478095:ios:df06af22987fea31645b7a',
    messagingSenderId: '297570478095',
    projectId: 'my-diplom-firebase',
    storageBucket: 'my-diplom-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseDiplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANiUGxyO75D9WAM-mkOHx-e5L9cXTgFro',
    appId: '1:297570478095:web:bd2a636582bc173a645b7a',
    messagingSenderId: '297570478095',
    projectId: 'my-diplom-firebase',
    authDomain: 'my-diplom-firebase.firebaseapp.com',
    storageBucket: 'my-diplom-firebase.appspot.com',
  );
}
